# Generated by Django 3.2.16 on 2023-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0004_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
