# Generated by Django 3.2.16 on 2023-07-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0005_club_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(default='pending', max_length=40, null=True),
        ),
    ]
