# Generated by Django 3.2.16 on 2023-07-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0012_complaint_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
